# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'WeatherLeBonCoin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.8.2'

end
